# Generated by Django 3.1.2 on 2020-10-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('currency', models.CharField(choices=[('01', 'Canadian Dollar'), ('02', 'Euro'), ('03', 'US Dollar')], default=('01', 'Canadian Dollar'), max_length=2)),
                ('stock', models.IntegerField(default=0)),
                ('size', models.CharField(choices=[('00', 'Unknown'), ('01', 'XS'), ('02', 'S'), ('03', 'M'), ('04', 'L'), ('05', 'XL'), ('06', 'XXL')], default=('00', 'Unknown'), max_length=2)),
                ('colour', models.CharField(blank=True, max_length=300, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
