# Generated by Django 3.1.2 on 2020-10-02 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(db_index=True, max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('platform', models.CharField(choices=[('01', 'WOOCOMMERCE'), ('02', 'SHOPIFY')], max_length=2)),
                ('store_url', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('store_id', 'platform')},
            },
        ),
    ]
